import streamlit as st
import pandas as pd
import numpy as np

# --- 1. 페이지 설정 ---
st.set_page_config(page_title="EDA Agent Premium Report", layout="wide")

# --- 2. 사이드바: 리포트 모드 선택 ---
with st.sidebar:
    st.title("🎯 Report Control")
    mode = st.radio(
        "확인할 리포트 모드를 선택하세요.",
        ["🏢 사업팀 인사이트 모드", "🧪 분석가 데이터 진단 모드"]
    )
    st.divider()
    st.caption("분석 대상: 최근 3개월 Sim Only 가입자")

# --- 3. 메인 리포트 영역 ---
st.title(f"📊 최종 분석 리포트 ({mode})")
st.divider()

if "사업팀" in mode:
    # ---------------------------------------------------------
    # [사업팀용] 1~3번 항목
    # ---------------------------------------------------------
    t1, t2, t3 = st.tabs(["📊 1. 집단간 비교", "👤 2. 프로파일링", "📱 3. 채널 선호도"])
    
    with t1:
        st.subheader("📍 지표별 특징 Index (전체 대비)")
        idx_df = pd.DataFrame({
            "지표명": ["유튜브 시청시간", "야간 데이터사용", "주말 통화량", "멤버십 활용"],
            "Index": [242, 185, 110, 95]
        }).sort_values("Index", ascending=False)
        
        for _, row in idx_df.iterrows():
            col_l, col_r = st.columns([0.2, 0.8])
            col_l.write(f"**{row['지표명']}**")
            col_r.progress(min(row['Index']/300, 1.0), text=f"Index: {row['Index']}")
        
        st.subheader("🔍 변수별 예측력 (IV Rank)")
        iv_data = pd.DataFrame({"IV Score": [0.45, 0.32, 0.15, 0.08]}, 
                               index=["데이터사용량", "앱접속빈도", "연령", "가입기간"])
        st.bar_chart(iv_data)

    with t2:
        st.subheader("👥 고객 기본 프로파일링")
        c1, c2 = st.columns(2)
        with c1:
            st.write("**성별 비중**")
            st.table(pd.DataFrame({"비중(%)": [62, 38]}, index=["남성", "여성"]))
        with c2:
            st.write("**연령대 분포**")
            # 연령대 데이터 생성 및 히스토그램 설정
            age_data = pd.DataFrame(np.random.normal(28, 5, 100), columns=['연령'])
            # Streamlit 내장 차트의 축 레이블 가독성을 위해 데이터프레임 가공
            counts, bin_edges = np.histogram(age_data['연령'], bins=10)
            hist_df = pd.DataFrame({
                "연령대": [f"{int(bin_edges[i])}세" for i in range(len(counts))],
                "고객 수": counts
            }).set_index("연령대")
            
            # x축(연령대), y축(고객 수) 레이블 명시적 노출
            st.bar_chart(hist_df)
            st.caption("X축: 연령대 (세) / Y축: 고객 수 (명)")

    with t3:
        st.subheader("📣 채널 선호도 반응 분석")
        channel_data = pd.DataFrame({
            "반응": [45, 12, 28],
            "미반응": [55, 88, 72]
        }, index=["App Push", "MMS", "알림톡"])
        st.bar_chart(channel_data)

else:
    # ---------------------------------------------------------
    # [분석가용] 1~7번 항목 (에러 해결 버전)
    # ---------------------------------------------------------
    t1, t2, t3, t4 = st.tabs(["🧹 1-2. 클렌징/카디널리티", "📉 3. 이상치 영향도", "🔗 4-6. 상관관계/VIF", "📐 7. Binning 제안"])
    
    with t1:
        st.subheader("1-2️⃣ 데이터 클렌징 및 카디널리티")
        st.write("**Zero-Variance 변수 (제거 대상)**")
        st.table(pd.DataFrame({"변수명": ["is_active_user", "country_code"], "값": ["Y", "82"]}))
        
        st.write("**Cardinality 체크**")
        card_df = pd.DataFrame({
            "변수명": ["activity_area", "device_model", "cust_grade"],
            "Unique Count": [1450, 420, 5],
            "Status": ["⚠️ High", "⚠️ High", "✅ Normal"]
        })
        st.dataframe(card_df.style.highlight_max(axis=0, subset=["Unique Count"], color='lightcoral'))

    with t2:
        st.subheader("3️⃣ Outlier 영향도 분석 (제거 전/후)")
        c1, c2 = st.columns(2)
        c1.caption("이상치 제거 전 (Skewed)")
        c1.bar_chart(np.random.exponential(50, 15))
        c2.caption("이상치 제거 후 (Normal)")
        c2.bar_chart(np.random.normal(30, 5, 15))
        
        st.write("**통계량 변화율**")
        st.table(pd.DataFrame({"피처": ["data_usage_mb", "call_dur"], "변화율": ["-29.0%", "-1.9%"]}))

    with t3:
        st.subheader("4-6️⃣ 상관관계 및 다중공선성 진단")
        st.error("⚠️ VIF 위험 그룹: [total_data_mb, night_data_mb] - 다중공선성 높음")
        
        st.write("**상관계수 히트맵 (Heatmap)**")
        corr_data = pd.DataFrame(
            np.random.uniform(-1, 1, (5, 5)), 
            columns=['Age', 'Data', 'App', 'Call', 'Svc'], 
            index=['Age', 'Data', 'App', 'Call', 'Svc']
        )
        # matplotlib 설치 후 정상 작동하는 코드
        st.dataframe(corr_data.style.background_gradient(cmap='coolwarm').format("{:.2f}"))
        
        st.subheader("Feature-Target Correlation (Top 4)")
        target_corr = pd.DataFrame({"Corr": [0.65, 0.42, -0.35, 0.12]}, index=["data_usage", "complain", "svc_period", "age"])
        st.bar_chart(target_corr)

    with t4:
        st.subheader("7️⃣ 최적 Binning 구간 제안")
        st.write("**[피처: 서비스 가입 기간]**")
        bin_df = pd.DataFrame({
            "Target Rate(%)": [45.2, 22.5, 12.0, 5.1]
        }, index=["0-6m", "6-12m", "12-24m", "24m+"])
        st.bar_chart(bin_df)
        st.info("💡 가입 6개월 미만(Early Stage)의 해지 적중률이 가장 높으므로 집중 관리가 필요함")

# 공통 푸터
st.divider()
st.caption("Generated by Gen-AI EDA Agent v1.2")
